### ISSUE TITLE
using .json to get bookmarklets

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#1]
@gosoccerboy5 can I use your code?

**Comment by gosoccerboy5** [comment]
Sure, I'm not stopping you!

**Comment by Shluffy** [comment]
> Sure, I'm not stopping you!

okay. I will download and add it. of course the css will probably be like shluffy.github.io. do you know how to toggle light/dark mode by a button?

**Comment by gosoccerboy5** [comment]
```html
<button onclick="toggleTheme();">Switch theme</button>
```
```js
function toggleTheme() {
  document.body.class = (document.body.class === "dark"? "light": "dark");
}
```
```css
.dark {
  /* extra rules that override normal theme */
}
```
basic idea

**Comment by Shluffy** [comment]
> ```
> <button onclick="toggleTheme();">Switch theme</button>
> ```
> 
> ```js
> function toggleTheme() {
>   document.body.class = (document.body.class === "dark"? "light": "dark");
> }
> ```
> 
> ```css
> .dark {
>   /* extra rules that override normal theme */
> }
> ```
> 
> basic idea

okay, will work on that as well

**Comment by xItzDiamondx** [comment]
For the normal page, should I develop it?

**Comment by Shluffy** [comment]
> For the normal page, should I develop it?

we need a contributors page

**Comment by ZI-Youtuber** [comment]
@Shluffy yeah

**Comment by ZI-Youtuber** [comment]
@Shluffy well that will be in the Scratch Devs ebsite as well but if you are talking about specifically this repo then ok

**Comment by Shluffy** [comment]
> @Shluffy well that will be in the Scratch Devs website as well but if you are talking about specifically this repo then ok

both.

**Comment by Shluffy** [comment]
This is now done
