### ISSUE TITLE
Request contributors to be added by all-contributors (2)

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#105]
Issue 1: #62
note that everything will get reviewed before being added. Feel free to ask the bot to add someone.

How to request someone:
comment this call code: `@all-contributors please add @<contributor> for <reason>`. 
Replace `<contributor>` with the contributor to be added and `<reason>` with the reason they should be added. 
You can add multiple reasons separated with a comma (`,`).
 
List of reasons:

- Code (💻)
- Tests (⚠️)
- Bug Reports (🐛)
- Documentation (📖)
- Maintenance (🚧)
- Blog Posts (📝)
- Tools (🔧)
- Answering Questions (💬 )
- Ideas, Planning, & Feedback (🤔)
- Infrastructure (Hosting, Build-tools, etc) (🚇)
- Design (🎨)
- Content

See the full list [here](https://allcontributors.org/docs/en/emoji-key).

**Comment by xItzDiamondx** [comment]
K

**Comment by xItzDiamondx** [comment]
@all-contributors please add @xItzDiamondx for Design, Content, Infra, Maintenance, Bug Reports, Tests, Code.

**Comment by Shluffy** [comment]
@all-contributors please add @Shluffy for Maintenance, project Management

**Comment by Shluffy** [comment]
@all-contributors please add @Shluffy for tests

**Comment by ZI-Youtuber** [comment]
@all-contributors please add @ZI-Youtuber for Helping, Bug Reporter, Code , Documentation , Tests

**Comment by ZI-Youtuber** [comment]
@all-contributors please add @ZI-Youtuber  for Bug Reporter, Code , Documentation , Tests , Talk

**Comment by ZI-Youtuber** [comment]
@all-contributors please add @ZI-Youtuber for Bug Reporter, Code , Documentation , Tests, research, review, Ideas, Planning, & Feedback

**Comment by Shluffy** [comment]
@all-contributors pls add @theforumhelpers for code

**Comment by Shluffy** [comment]
@all-contributors pls add @ninjamar for code

**Comment by Shluffy** [comment]
@all-contributors pls add @ninjamar for bug

**Comment by Shluffy** [comment]
@all-contributors pls add @codeguy92 for bug and ideas

**Comment by imlens** [comment]
Make this a discussion @Shluffy

**Comment by Shluffy** [comment]
@NotDiamondZ won't work then

**Comment by Shluffy** [comment]
i will try to make an actions to remove it
