### ISSUE TITLE
Question: is it possible to run prettier on commits

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#135]
^. @FunctionalMetatable

**Comment by FunctionalMetatable** [comment]
After a commit is made we cannot change it so we make a new commit to run it through prettier

**Comment by FunctionalMetatable** [comment]
> well, after the commit like after the push

wdym?

**Comment by FunctionalMetatable** [comment]
> when you push it runs prettier, is it possible to do that on a commit?

do you mean running prettier on push and not making another commit to format the code? it doesn't look like this is possible

**Comment by Shluffy** [comment]
okay, ty
