### ISSUE TITLE
Bug: My contribution box is narrow on the readme.md

### ISSUE THREAD

**Issue by ZI-Youtuber** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#142]
**Describe the bug**

My part of contributions is narrow

**Additional context**

Maybe just put me in the next row

**Comment by Shluffy** [comment]
this is because of the contributors per line set at 7. feel free to make a pr to change that

**Comment by ZI-Youtuber** [comment]
@Shluffy I don't know how to do that. Isn't it possible to put me in the next row?

**Comment by Shluffy** [comment]
@FunctionalMetatable Would we have to manually change the rows when we change contribs per line.
@ZI-Youtuber are you on mobile? this could be screen size

**Comment by FunctionalMetatable** [comment]
@all-contributors please add @gosoccerboy5 for feedback

**Comment by FunctionalMetatable** [comment]
@all-contributors please add @gosoccerboy5 for content

**Comment by FunctionalMetatable** [comment]
okay lets try something else add @brourbeinsus for data @all-contributors

**Comment by FunctionalMetatable** [comment]
@all-contributors add @brourbeinsus for data

**Comment by FunctionalMetatable** [comment]
Fixed in https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/commit/96717562d48b8237eef2b5bc8aa59d6287269fd8

**Comment by ZI-Youtuber** [comment]
@FunctionalMetatable thanks
