### ISSUE TITLE
Bug:  New Issue with recent update to mergify.yml by Shluffy

### ISSUE THREAD

**Issue by ZI-Youtuber** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#146]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82158378/120343042-4590f700-c2f0-11eb-8eb8-3c51d9d1f4b1.png)

Showed a cross meaning not all checks were passed and there was an error with one check

![image](https://user-images.githubusercontent.com/82158378/120343202-6d805a80-c2f0-11eb-84c3-8183979ee0a8.png)

![image](https://user-images.githubusercontent.com/82158378/120343254-77a25900-c2f0-11eb-8dce-b5a505791140.png)

**Expected behavior**

Normally would show a tick when all checks passed

**Browser Information**

Using Windows 10 as my OS
Using Chrome as my Browser

**Additional context**

Nothing Really

**Comment by Shluffy** [comment]
I am aware that mergify is currently not working perfectly and am looking into it.

**Comment by ZI-Youtuber** [comment]
@Shluffy ok

**Comment by ZI-Youtuber** [comment]
@Shluffy Is there anything I can help with this issue and mergify
