### ISSUE TITLE
Feature Request: Use the wiki page for this repository

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#147]
**Feature**

use the wiki page

**Comment by Shluffy** [comment]
unless should we put it on our website like scratch addons does?

**Comment by Shluffy** [comment]
I will work on putting the wiki onto a branch on my fork. Note that if we would update the actual in repo wiki it will likely not update forks.

**Comment by ZI-Youtuber** [comment]
@Shluffy I'm making wiki as well for my own project so what you can do is make a serperate repository and when you enable the github pages chnage the /root to /docs and choose a thememe and then all you have to do is go to the coding files and go to docs file and just go to the readme.md and start writing and you will have to make each section with ## to make it a section on readme.md

**Comment by Shluffy** [comment]
would that include everything else? i think keeping it all in 1 repo is good

**Comment by ZI-Youtuber** [comment]
@Shluffy Sadly it won't include everthing else but you can add a link to the main website. And if you put it in one repo it will not work

**Comment by ZI-Youtuber** [comment]
so you will have to make a separate repo. If you want I can be a good help for the wiki if you make a new repo and add me as a maintainer in it so I can configure everything quickly @Shluffy 

> @Shluffy Sadly it won't include everthing else but you can add a link to the main website. And if you put it in one repo it will not work

**Comment by Shluffy** [comment]
> so you will have to make a separate repo. If you want I can be a good help for the wiki if you make a new repo and add me as a maintainer in it so I can configure everything quickly @Shluffy
> 
> > @Shluffy Sadly it won't include everthing else but you can add a link to the main website. And if you put it in one repo it will not work

putting the wiki in this repo should work? why wouldn't it @ZI-Youtuber

**Comment by ZI-Youtuber** [comment]
@Shluffy I don't know why it is just that I have found out from github it wouldn't work

**Comment by Shluffy** [comment]
i also deleted a bunch of my comments to
