### ISSUE TITLE
Getting a domain and hosting from Fosshost

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#148]
@xItzDiamondx have you gotten a response from fosshost about a domain?

**Comment by Shluffy** [comment]
@xItzDiamondx ?

**Comment by xItzDiamondx** [comment]
Hi. I'm just seeing this as I am on summer break. I'll check.

**Comment by xItzDiamondx** [comment]
They rejected @Shluffy
