### ISSUE TITLE
Feature Request: Footer

### ISSUE THREAD

**Issue by gosoccerboy5** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#16]
**Feature**
With all of the new pages we are planning on adding, we should have a footer

**Additional context**
#13 #9 #15

Probably done best with JS, but we can do an \<embed> or \<iframe> like tfh once did

**Comment by Shluffy** [comment]
Yea, I only know how to make html header which is hard to upkeep in the long run.

**Comment by gosoccerboy5** [comment]
They're not too hard to make

**Comment by xItzDiamondx** [comment]
Footer is this:
`<footer class="my-amazing-footer><p>Your info here!</p></footer>"`

**Comment by Shluffy** [comment]
We should also make a header.

**Comment by Shluffy** [comment]
go for it if you want - we should definitley have a header and footer

**Comment by xItzDiamondx** [comment]
Should the header be a navigation bar? I mean, I have one at
xItzDiamondx/Responsive-Web-Navigation-Bar (Not sure if the link will work)

**Comment by xItzDiamondx** [comment]
Of course it doesn't work. [Here.](https://github.com/xItzDiamondx/Responsive-Web-Navigation-Bar/)

**Comment by Shluffy** [comment]
A nav bar? I think that might work

**Comment by xItzDiamondx** [comment]
I'll start developing it.

**Comment by xItzDiamondx** [comment]
I'll close this because it has been added into the site.
