### ISSUE TITLE
Feature Request: add a favicon

### ISSUE THREAD

**Issue by gosoccerboy5** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#18]
**Feature**
we want a [favicon](https://en.wikipedia.org/wiki/Favicon)

**Additional context**
none

also, github automatically adds a favicon to pages I believe

**Comment by ZI-Youtuber** [comment]
@gosoccerboy5 Yeah I think it is a good idea to add a favion but you have to use some html code to put the favicon since github-pages doesn't automaically add it

**Comment by xItzDiamondx** [comment]
We have to come up with an aesthetic icon, that icon should also be the org
pfp. I know the code for adding a favicon, but I'm not the best artist.
I'll look online for a logo maker.

**Comment by xItzDiamondx** [comment]
By the way, we also should have a email where people can contact us. All of
us should have access to it. I recommend ProtonMail. Also, in my website at
the footer I have some cool stuff like the footer, copyright, email, ans
stuff. Check it out.

**Comment by xItzDiamondx** [comment]
For the favicon (sorry for many messages) what is our catchphrase?

**Comment by xItzDiamondx** [comment]
I'm on it.

**Comment by xItzDiamondx** [comment]
https://vectr.com/tmp/b3miAu9oaz/a1e6B5S0EU.svg?width=640&height=640&select=a1e6B5S0EUpage0 How does this look @Shluffy @gosoccerboy5

**Comment by xItzDiamondx** [comment]
![image](https://user-images.githubusercontent.com/81493936/118305315-644c5c80-b4ad-11eb-9cd3-4d06cc16c2db.png)

**Comment by gosoccerboy5** [comment]
Still gotta merge the actual favicon..

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx looks epic
