### ISSUE TITLE
Bug: Prettier is failing

### ISSUE THREAD

**Issue by xItzDiamondx** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#184]
**Describe the bug**

The GH Action Prettier is failing on every PR. Please fix this
**To Reproduce**
Not reproduceable.

**Expected behavior**
It's supposed to work

**Browser Information**

ChromeOS Version 91.0.4472.81 (Official Build) (64-bit)
**Additional context**

NONE

**Comment by Shluffy** [comment]
@FunctionalMetatable does prettier

**Comment by FunctionalMetatable** [comment]
not my fault, the latest commit created malformed json in bookmarklets.json

**Comment by Shluffy** [comment]
alright, this is just malformed json. we may want to look into the malformed json, but this is going to be labeled as invalid.

**Comment by NotDiamondZ** [comment]
I'll work on this.

**Comment by xItzDiamondx** [comment]
Solved in commit 5f713fc993b18510d09e5aec6369e651a327a7f1 and b5c833f43cdd0cdd96136699d6911908b04eb8eb
