### ISSUE TITLE
Feature Request: rewrite in nuxt

### ISSUE THREAD

**Issue by FunctionalMetatable** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#185]
we need more styling

**Comment by Shluffy** [comment]
i don't know nuxt. feel free to make a pr adding this and i will look at it

**Comment by FunctionalMetatable** [comment]
or plain vue?

**Comment by Shluffy** [comment]
yea

**Comment by Shluffy** [comment]
okay. this is not going anywhere so I will close this. feel free to reopen later or make a new issue
