### ISSUE TITLE
Feature Request: Better Styling

### ISSUE THREAD

**Issue by LankyBox01** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#189]
https://scratch-bookmarklets.github.io/
Please make the dark logos white. It just hurts my eyes

**Comment by Shluffy** [comment]
@xItzDiamondx pls do more on the css. maybe make themes, or use black and white rather then this color theme

**Comment by NotDiamondZ** [comment]
I have a template [here](https://github.com/xItzDiamondx/dark-mode), but I'm just afraid that it will mess up the entire sites functionality.

**Comment by NotDiamondZ** [comment]
I'll try it locally on Visual Studio Code.

**Comment by NotDiamondZ** [comment]
I'm gonna solve this using https://darkmodejs.learn.uno/

**Comment by NotDiamondZ** [comment]
@CodeGuy92 and @Shluffy, update. If I add dark mode, it will break the mobile friendlyness. Which is better? Or should we have a seperate site with dark mode and our main mobile friendly?

**Comment by Shluffy** [comment]
> @CodeGuy92 and @Shluffy, update. If I add dark mode, it will break the mobile friendlyness. Which is better? Or should we have a seperate site with dark mode and our main mobile friendly?

we can add a `/mobile/` directory to the site

**Comment by NotDiamondZ** [comment]
We sure can. I'll remove the mobile functionality locally then push using Git.

**Comment by NotDiamondZ** [comment]
BTW shluffy, you can download VS Code on ur cb

**Comment by Shluffy** [comment]
Make a new branch that adds the mobile directory. I can do that.

**Comment by Shluffy** [comment]
did some triage updates to this issue

**Comment by NotDiamondZ** [comment]
Instead of a branch I think it should be a folder in master. Then we have all the other scripts in there but modified for mobile friendlyness

**Comment by NotDiamondZ** [comment]
I'll add it

**Comment by Shluffy** [comment]
> Instead of a branch I think it should be a folder in master. Then we have all the other scripts in there but modified for mobile friendlyness

no, a branch to make it on and then merge it into `master`. sorry that I was unclear

**Comment by NotDiamondZ** [comment]
Ah. OK

**Comment by NotDiamondZ** [comment]
I'll do it

**Comment by CodeGuy92** [comment]
yay
