### ISSUE TITLE
Remove All of the bookmarklet js files

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#19]
now all in .json file, so not really needed

**Comment by Shluffy** [comment]
@gosoccerboy5 would this work?

**Comment by gosoccerboy5** [comment]
I suppose gathering from the website works too. Sure, I'd be fine with that. Besides, we have git, so we can revert anytime.

**Comment by Shluffy** [comment]
I will do that. Also, why are there random slashes in the .json file?
