### ISSUE TITLE
Feature Request: Add scratch-bookmarklets domain

### ISSUE THREAD

**Issue by CodeGuy92** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#190]
I can get that domain and add it to your site if you want.

**Comment by CodeGuy92** [comment]
scratch-bookmarklets.tk

**Comment by Shluffy** [comment]
Nice! I would prefer a more broad one, like `.com`, `.net`, `.org`, etc. rather then one like `.tk`, whick according to wikipedia ".tk is the Internet country code top-level domain (ccTLD) for Tokelau, a territory of New Zealand in the South Pacific.", and this is not for Tokelau

**Comment by Shluffy** [comment]
if possible to get a domain like the ones that I mentioned, I don't really know how to add a domain using github (otherwise I would use my domain for stuff like that). How do you do that?

**Comment by Shluffy** [comment]
see https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/issues/92#issuecomment-847262813, #92, and #148

**Comment by CodeGuy92** [comment]
scratch-bookmarklets.tk
scratch-bookmarklets.ml
scratch-bookmarklets.ga
scratch-bookmarklets.cf
scratch-bookmarklets.gq

scratchbookmarklets.tk
scratchbookmarklets.ml
scratchbookmarklets.ga
scratchbookmarklets.cf
scratchbookmarklets.gq

bookmarkletsforscratch.tk
bookmarkletsforscratch.ml
bookmarkletsforscratch.ga
bookmarkletsforscratch.cf
bookmarkletsforscratch.gq

You can choose one of them that you want.

**Comment by Shluffy** [comment]
again these all are using endings for a specific place. Between these though, I think `scratch-bookmarklets.cf`

**Comment by NotDiamondZ** [comment]
Ah. I see. He is using Freenom. Try using [Fosshost](fosshost.org/apply) They give you it for free but first you have to be approved.

**Comment by NotDiamondZ** [comment]
I'm doing a `.com` domain

**Comment by NotDiamondZ** [comment]
Ok. Update: To get the domain, you have to choose another service.
@Shluffy?
![image](https://user-images.githubusercontent.com/83427897/124649774-c55d3480-de4d-11eb-9e81-1c8026d503c2.png)

**Comment by NotDiamondZ** [comment]
I'm gonna do AArch64 VPS. It's a Virtual Private Server. We can store our images and stuff on there.

**Comment by xItzDiamondx** [comment]
I'll close this issue for now.

**Comment by NotDiamondZ** [comment]
THEY ALREADY SAID NO WTF

**Comment by NotDiamondZ** [comment]
We'll try again in 6 months.

**Comment by xItzDiamondx** [comment]
If you don't need me here, I'll leave. I'll remove all my commits and everything.

**Comment by xItzDiamondx** [comment]
I do 123 commits and more than 1k additions and y'all don't appreciate. I'm done.

**Comment by Shluffy** [comment]
@xItzDiamondx We want you to stay. Was it the block? either way being an org member/maintainer meant that it made no difference.

**Comment by Shluffy** [comment]
Pls email me to talk about it

**Comment by FunctionalMetatable** [comment]
> If you don't need me here, I'll leave. I'll remove all my commits and everything.

I should be leaving not you

**Comment by xItzDiamondx** [comment]
Really, how?
