### ISSUE TITLE
Can I open a project?

### ISSUE THREAD

**Issue by gosoccerboy5** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#20]
https://docs.github.com/en/github/managing-your-work-on-github/about-project-boards

I've never made a project or project board, but since we have ideas for multiple pages on the website, maybe it'd be best to organize all the webpage ideas into one project
@Shluffy

**Comment by Shluffy** [comment]
go for it.

**Comment by Shluffy** [comment]
I really should give you admin to the repo. I am doing that now

**Comment by gosoccerboy5** [comment]
[done](https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/projects/1)
