### ISSUE TITLE
Feature Request: Alert User There May Be New Update Available

### ISSUE THREAD

**Issue by NotDiamondZ** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#202]
**Feature**
Alerts users that there may be a new update for that bookmarklet

In the JS, we could make a variable like this:
`var release = 'v0.1';`
Then we would make it look for a version maybe with [Shields](shields.io).
**Additional context**

None

**Comment by NotDiamondZ** [comment]
cc @FunctionalMetatable @Shluffy

**Comment by NotDiamondZ** [comment]
We also need to fix @github-actions

**Comment by Shluffy** [comment]
if you have an idea you can make a pr

**Comment by xItzDiamondx** [comment]
I'm not that good with JS so I thought you or Function could do it
