### ISSUE TITLE
Bug: Can Edit Text area

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#22]
**Describe the bug**
![image](https://user-images.githubusercontent.com/81823039/118173065-1aa33980-b3fb-11eb-9303-dc440a87bec1.png)

**To Reproduce**
change the text in the text area

**Expected behavior**

unchnageable

**Browser Information**

Google Chrome | 91.0.4472.33 (Official Build) beta (64-bit)
-- | --
Revision | 35d909982aeb034113732460de33d77009059efa-refs/branch-heads/4472@{#659}
Platform | 13904.22.0 (Official Build) beta-channel octopus

**Additional context**
@gosoccerboy5 was this on purpose? I know of  a simple fix for this.

**Comment by gosoccerboy5** [comment]
I would have made readonly="true", but I figured people might want to edit the bookmarklet to their liking before bookmarking it.
Go ahead and change that - no one's going to be able to edit the bookmarklet beforehand anyways because it automatically selects the text.

**Comment by Shluffy** [comment]
We could leave it as a separate page. What do you think about that?
