### ISSUE TITLE
Copy all code from repo to main org's repo

### ISSUE THREAD

**Issue by ZI-Youtuber** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#30]
I need to copy the code for the webiste and put it on the main org repo so can you amke a seperate branch containging only the website code

**Comment by xItzDiamondx** [comment]
What do you mean?

**Comment by ZI-Youtuber** [comment]
@ZI-Youtuber make seate branch in repo for website code

**Comment by ZI-Youtuber** [comment]
@Shluffy @gosoccerboy5 @xItzDiamondx 
Oh wait this is the repo only for website not for the bookmarklets right?

**Comment by xItzDiamondx** [comment]
@gosoccerboy5 and @Shluffy decided to put the bookmarklets in the site with
some JSON

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx ok.

**Comment by ZI-Youtuber** [comment]
@Scratch-Bookmarklets/whole-org Is there anyway I can copy this whole repo coding files and paste them on the  main repo on the main org?

**Comment by xItzDiamondx** [comment]
You can fork it.

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx But it wouldn't be even with the main repo that's the problem

**Comment by xItzDiamondx** [comment]
This is how to update it: 

https://user-images.githubusercontent.com/81493936/118378314-98e91280-b598-11eb-9d31-78713bdabff6.mp4
Recorded on OBS Studio for MacOS

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx I know hoe to do that but I was saying without forking it
