### ISSUE TITLE
Theme Colors

### ISSUE THREAD

**Issue by xItzDiamondx** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#31]
Hey, I'm developing the site. What should our theme colors be? Orange and red?

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx you mean the main org one

**Comment by xItzDiamondx** [comment]
This org.

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx the main org website?

**Comment by xItzDiamondx** [comment]
Yes. This repo

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx no i'm talking about the Scratch Devs Team one

**Comment by xItzDiamondx** [comment]
What about it.

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx Are you doing that as well?

**Comment by xItzDiamondx** [comment]
Sure.

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx Orange and red sounds good for the Scratch Bookmarlets website

**Comment by ZI-Youtuber** [comment]
> Sure.

ok

**Comment by xItzDiamondx** [comment]
This shade?

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx what shade

**Comment by xItzDiamondx** [comment]
![Screenshot 2021-05-14 1 23 34 PM](https://user-images.githubusercontent.com/81493936/118312848-9d89ca00-b4b7-11eb-81ad-ed08371e0138.png)
![Screenshot 2021-05-14 1 23 31 PM](https://user-images.githubusercontent.com/81493936/118312850-9e226080-b4b7-11eb-8d7c-d34254844b38.png)

**Comment by xItzDiamondx** [comment]
They kind of don't work together.

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx Don't do blue do red

**Comment by xItzDiamondx** [comment]
There is red and blue.

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx Orange and red because that how it looks like in the logo

**Comment by xItzDiamondx** [comment]
ok

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx it will go well

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx 👍

**Comment by xItzDiamondx** [comment]
These two?
![Screenshot 2021-05-14 1 25 30 PM](https://user-images.githubusercontent.com/81493936/118313058-e2adfc00-b4b7-11eb-96cd-7685d46d7df5.png)
![Screenshot 2021-05-14 1 25 28 PM](https://user-images.githubusercontent.com/81493936/118313059-e2adfc00-b4b7-11eb-92a3-41a09eeeb69f.png)

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx yep

**Comment by xItzDiamondx** [comment]
Ok. I'm doing orange as the main and red as second.

**Comment by ZI-Youtuber** [comment]
@Scratch-Bookmarklets/whole-org Wow this has been a busy day for me today working on github

**Comment by ZI-Youtuber** [comment]
> Ok. I'm doing orange as the main and red as second.

ok your choice if @Shluffy @gosoccerboy5 agrees

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx Remeber to do it orange and red

**Comment by Shluffy** [comment]
i think those are good

**Comment by ZI-Youtuber** [comment]
@Shluffy yeah

**Comment by xItzDiamondx** [comment]
I'm closing it for now. I'll make a PR with the rest of my changes later.
