### ISSUE TITLE
Feature Request:  Let people easily copy the javascript code

### ISSUE THREAD

**Issue by ZI-Youtuber** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#32]
**Feature**
I think people should be able to copy the code easily so there should be some way we could do it

**Additional context**
@xItzDiamondx @Shluffy @ZI-Youtuber @gosoccerboy5

**Comment by gosoccerboy5** [comment]
This is already essentially done. It autoselects the code

at least it did, before you guys changed everything while I was eating lunch

**Comment by ZI-Youtuber** [comment]
@gosoccerboy5 oh ok but @xItzDiamondx chnaged the whole lot 😒

**Comment by ZI-Youtuber** [comment]
@gosoccerboy5 like right  now

**Comment by gosoccerboy5** [comment]
Great. Just when I was settling in.

**Comment by ZI-Youtuber** [comment]
@gosoccerboy5 😆

**Comment by xItzDiamondx** [comment]
I was thinking we could put it on the Projects page and make buttons that
would copy it along with some fancy CSS.

**Comment by Shluffy** [comment]
we should add buttons to copy the code

**Comment by xItzDiamondx** [comment]
Exactly

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx @Shluffy yep

**Comment by gosoccerboy5** [comment]
The thing is, 
a) it's easy to copy the code if it autoselects
b) the main purpose of this is for bookmarklets, so all you need to do is select the code without having to copy it

**Comment by xItzDiamondx** [comment]
Look: [W3 Schools](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp)

**Comment by xItzDiamondx** [comment]
We could do that but without the input box.

**Comment by xItzDiamondx** [comment]
I'll start on it.

**Comment by xItzDiamondx** [comment]
I'll close it for now.

**Comment by xItzDiamondx** [comment]
I'm working on it right now on my test @NotDiamondZ
