### ISSUE TITLE
reminder

### ISSUE THREAD

**Issue by gosoccerboy5** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#33]
Please, don't push excessive commits to this repo. INSTEAD, please work locally on your fork, and when you have enough commits on a branch, _then_ you make a pull request. 
Also, make sure something is approved until merging a PR.

Otherwise, we end up with a constantly broken site with a bunch of merge conflicts and difficulty making large changes.

Thanks.

**Comment by xItzDiamondx** [comment]
Okay sorry.

**Comment by ZI-Youtuber** [comment]
@gosoccerboy5 ok

**Comment by gosoccerboy5** [comment]
> Okay sorry.

Its fine, I shouldnt have been so frustrated

**Comment by ZI-Youtuber** [comment]
@gosoccerboy5 😄
