### ISSUE TITLE
Feature Request:  Put contribters side by side

### ISSUE THREAD

**Issue by ZI-Youtuber** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#34]
Make the contributers smaller an put them side by side

**Comment by xItzDiamondx** [comment]
I'll try

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx ok

**Comment by xItzDiamondx** [comment]
It requires CSS and because the README is markdown, it is just impossible.
They support HTML, but not CSS for some reason. That is why I'm closing
this.

**Comment by Shluffy** [comment]
let's please not assign everyone.
