### ISSUE TITLE
What do you mean by Organization Wide Developer

### ISSUE THREAD

**Issue by ZI-Youtuber** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#35]
It says that I am an Organization Wide Developer in the contributers section I just wanted to know what it means

**Comment by xItzDiamondx** [comment]
Dunno. Ask @Shluffy for some ranks.

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx Shluffy thought of this?

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx the rank?

**Comment by ZI-Youtuber** [comment]
@Shluffy Do you know what it means by Organization Wide Developer?

**Comment by xItzDiamondx** [comment]
No, I thought of it. This isn't related to the website, so it will be closed.
