### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by ZI-Youtuber** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#37]
@Shluffy Put the logo that @xItzDiamondx made and put it as the logo of this org

@xItzDiamondx Can you make a logo for the Scratch Devs Team

**Comment by xItzDiamondx** [comment]
sure

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx thanks

**Comment by xItzDiamondx** [comment]
This isn't really a problem, so I'm closing.
