### ISSUE TITLE
Should I delete main org?

### ISSUE THREAD

**Issue by ZI-Youtuber** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#38]
I think I should delte the main org so @Shluffy you can remove the part about the Scratch Devs Team.

If anyone agrees pls tell me here.

@Shluffy Update the logo of the org to the one @xItzDiamondx made

**Comment by xItzDiamondx** [comment]
Dunno. Your choice.

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx let's wait for a reply from @Shluffy @gosoccerboy5

**Comment by Shluffy** [comment]
and the close this? sure - nothing is going on their

**Comment by Shluffy** [comment]
i see you done
