### ISSUE TITLE
Bug: Error with fetch

### ISSUE THREAD

**Issue by gosoccerboy5** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#4]
**Describe the bug**
Using a relative url in fetch makes it impossible to test locally, because you apparently can't fetch your own filesystem (!)

**To Reproduce**
Test index.html locally

**Expected behavior**
It should work locally.

**Browser Information**
MacOS Big Sur 2020, Firefox 88.0

**Additional context**
None.

**To fix**
we should use an absolute url in https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/blob/d6c51c7f0f3552eba5595a86523241f73a75921f/index.html#L11-L13
all you'll have to do is replace "bookmarklets.json" with "https://scratch-bookmarklets.github.io/bookmarklets.json"

**Comment by ZI-Youtuber** [comment]
@gosoccerboy5 well the url will stay the same to be honest

**Comment by gosoccerboy5** [comment]
> @gosoccerboy5 well the url will stay the same to be honest

Do you even know what I'm talking about? Try testing index.html locally - it won't work (unless this is a browser/os-specific thing)

**Comment by ZI-Youtuber** [comment]
@gosoccerboy5 we are using github-pages so it will write the file name obviously also with the part  "https://scratch-bookmarklets.github.io/"

And it happens with a lot of website other than the websites that uses github-pages

**Comment by Shluffy** [comment]
I will test locally.

**Comment by gosoccerboy5** [comment]
I can go ahead and make a pr
https://github.com/gosoccerboy5/Scratch-Bookmarklets.github.io/tree/use-absolute-url
