### ISSUE TITLE
Reminder 2.0 and 3.0 and 4.0

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#41]
2.0:
If there is a review pending, please don't merge. Either me or @gosoccerboy5 should approve before merging - possibly both.
Just request review.
cc @ZI-Youtuber @xItzDiamondx 

3.0:
please don't assign everybody. Assign someone to see it from the templates, and then the only person assigned should be the one who will be fixing it.

4.0:
please do all of your commits in prs on your fork - I am now going through some edits because of this. I have made someone's access read because of this.

**Comment by Shluffy** [comment]
like #39

**Comment by gosoccerboy5** [comment]
You might be able to edit my reminder 1.0

**Comment by Shluffy** [comment]
@ZI-Youtuber and @gosoccerboy5 and @xItzDiamondx please see reminder 4.0

**Comment by ZI-Youtuber** [comment]
@Shluffy ok

**Comment by xItzDiamondx** [comment]
@Zi-YouTuber did that, not me. I requested for a review but he merged.
