### ISSUE TITLE
Bug: site not loading

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#43]
github is saying the site is nonexistent. 
@gosoccerboy5 can you look into this.

**Comment by ZI-Youtuber** [comment]
@Shluffy yeah this has happened before to my websites on github. I will check it out

**Comment by ZI-Youtuber** [comment]
@Shluffy Maybe check the pages section on settings and see what url github put on

**Comment by Shluffy** [comment]
@ZI-Youtuber https://scratch-bookmarklets.github.io/

**Comment by xItzDiamondx** [comment]
I'll look into it. Weird.

**Comment by xItzDiamondx** [comment]
It's back up.
