### ISSUE TITLE
recent changes

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#46]
@ZI-Youtuber why did you make the changes recently? can you pls make a pr to revert that and then make a pr to do those changes with an explanation of why as well.

**Comment by ZI-Youtuber** [comment]
@ZI-Youtuber just merged pull requests thats all and some chnages to code

**Comment by Shluffy** [comment]
> @ZI-Youtuber just merged pull requests thats all and some chnages to code

so the code changes were not approved. Pls undo that and then make a pr using the template to get it possibly added.

**Comment by Shluffy** [comment]
@ZI-Youtuber basically said no.
![Screenshot 2021-05-23 2 10 32 PM](https://user-images.githubusercontent.com/81823039/119271717-af165480-bbd0-11eb-912e-a2d15847ce11.png)
@xItzDiamondx
