### ISSUE TITLE
Feature Request: link the contributers github

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#48]
**Feature**
link the contributers github.

**Additional context**
possibly also link scratch.

**Comment by xItzDiamondx** [comment]
Link who's Scratch? Like a studio or just a user?

**Comment by Shluffy** [comment]
user

**Comment by xItzDiamondx** [comment]
Who?

**Comment by Shluffy** [comment]
> Who?

the contributer. and there github

**Comment by xItzDiamondx** [comment]
It's for the source code. Not the user. Your choice though.
