### ISSUE TITLE
Feature Request: Read Download Visual Studio Code

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#49]
on multiple pages.
@xItzDiamondx you seem to have started, are you able to do it all in 1 pr

**Comment by xItzDiamondx** [comment]
What do you mean? Please describe more.

**Comment by Shluffy** [comment]
@ZI-Youtuber seemed to have removed that on multiple pages. #46 is there and hasn't been fixed yet

**Comment by xItzDiamondx** [comment]
The VS Code logo? That's because I'm developing it on VS Code. I'll revert it then PR it.

**Comment by xItzDiamondx** [comment]
I can't seem to revert it, can you?

**Comment by Shluffy** [comment]
> I can't seem to revert it, can you?

no. it has to be done manually. @ZI-Youtuber this is a job for you to fix

**Comment by xItzDiamondx** [comment]
K

**Comment by Shluffy** [comment]
@ZI-Youtuber left the org so I will have to do this

**Comment by Shluffy** [comment]
I can't figure out where and what commits

**Comment by Shluffy** [comment]
will leave as is.
