### ISSUE TITLE
Feature Request: alert user if they have clicked a scratch bookmarklet not on scratch

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#53]
**Feature**
alert user if they have clicked a scratch bookmarklet not on scratch

**Comment by xItzDiamondx** [comment]
good idea

**Comment by Shluffy** [comment]
more to this, how would we check the `/projects/*/editor/` for the display stage on left side

**Comment by Shluffy** [comment]
I'm gonna do the `parser.hostname` without the rest.

**Comment by xItzDiamondx** [comment]
OK.

**Comment by Shluffy** [comment]
i backlogged this. not being worked on, maybe will work on if i have time

**Comment by Shluffy** [comment]
i am gonna work on this

**Comment by Shluffy** [comment]
using window.location

**Comment by Shluffy** [comment]
unlinked pr

**Comment by xItzDiamondx** [comment]
Closing for now. Is very inactive.
