### ISSUE TITLE
Feature Request: add the all-contributors app to this repo

### ISSUE THREAD

**Issue by FunctionalMetatable** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#58]
**Feature**
Add the all-contributors app to the repo so we can easily add contributors to the readme

**Comment by Shluffy** [comment]
what app is this? I have only been on github for a month

**Comment by xItzDiamondx** [comment]
This repo?

>

**Comment by xItzDiamondx** [comment]
I've requested to install it

**Comment by Shluffy** [comment]
This has been installed. @FunctionalMetatable is there any more setup? if so, can you please do that. Also, do you want to be part of the org or have read/write access to this repo?

**Comment by xItzDiamondx** [comment]
You may get read/write access because you have been PRing and it is mostly
getting approved.

**Comment by Shluffy** [comment]
@all-contributors please add @Shluffy for being "alive"

**Comment by Shluffy** [comment]
@all-contributors please add @FunctionalMetatable for bookmarklets

**Comment by Shluffy** [comment]
@all-contributors please add @FunctionalMetatable for code

**Comment by FunctionalMetatable** [comment]
please could i have read/write access to this repo?

**Comment by Shluffy** [comment]
> please could i have read/write access to this repo?
> /cc @Shluffy / @xItzDiamondx

yes. 
if you want to, pls fill this out:
Do you want to be a codeowner on anything?
Do you want to be assigned to bug reports or feature requests?
Do you want to join the org?

/cc @brourbeinsus @xItzDiamondx @gosoccerboy5 feel free to fill this out to be added

**Comment by FunctionalMetatable** [comment]
> Do you want to be a codeowner on anything?
> Do you want to be assigned to bug reports or feature requests?
> Do you want to join the org?

1. maybe the .github files (i need to fix something there)
2. no thanks
3. no thanks im good
also, thanks for inviting!

**Comment by Shluffy** [comment]
> > Do you want to be a codeowner on anything?
> > Do you want to be assigned to bug reports or feature requests?
> > Do you want to join the org?
> 
> 1. maybe the .github files (i need to fix something there)
> 2. no thanks
> 3. no thanks im good
>    also, thanks for inviting!

feel free to open a pr to add yourself then!

**Comment by Shluffy** [comment]
done

**Comment by Shluffy** [comment]
@FunctionalMetatable this is SO useful

**Comment by FunctionalMetatable** [comment]
> @FunctionalMetatable this is SO useful

very confusing as well lol
