### ISSUE TITLE
Request contributors to be added by all-contributors

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#62]
note that everything will get reviewed before being added. Feel free to ask the bot to add someone.

How to request someone:
comment this call code: `@all-contributors please add @<contributor> for <reason>`. 
Replace `<contributor>` with the contributor to be added and `<reason>` with the reason they should be added. 
You can add multiple reasons separated with a comma (`,`).
 
List of reasons:

- Code (💻)
- Tests (⚠️)
- Bug Reports (🐛)
- Documentation (📖)
- Maintenance (🚧)
- Blog Posts (📝)
- Tools (🔧)
- Answering Questions (💬 )
- Ideas, Planning, & Feedback (🤔)
- Infrastructure (Hosting, Build-tools, etc) (🚇)
- Design (🎨)
- Content

**Comment by Shluffy** [comment]
@all-contributors please add @Shluffy for Tests

**Comment by Shluffy** [comment]
@all-contributors please add @Shluffy for code

**Comment by FunctionalMetatable** [comment]
@all-contributors please add @FunctionalMetatable for code, test

**Comment by Shluffy** [comment]
@all-contributors please add @xItzDiamondx  for design

**Comment by Shluffy** [comment]
@all-contributors please add @<contributor> for design, Infrastructure, Bug Reports, Ideas, Planning, & Feedback

**Comment by Shluffy** [comment]
@all-contributors please add @Shluffy for design, Infrastructure, Bug Reports, Ideas, Planning, & Feedback

**Comment by Shluffy** [comment]
@all-contributors please add @gosoccerboy5 for design, Infrastructure, Bug Reports, Ideas, Planning, & Feedback, Code, Tests

**Comment by Shluffy** [comment]
@all-contributors please add @xItzDiamondx for design, Infrastructure, Bug Reports, Ideas, Planning, & Feedback, Code, Tests

**Comment by Shluffy** [comment]
@all-contributors please add @allcontributors for documentation

**Comment by Shluffy** [comment]
@all-contributors please add @all-contributors for documentation

**Comment by Shluffy** [comment]
@all-contributors please add @gosoccerboy5 for design, Infrastructure, Bug Reports, Ideas, Planning, & Feedback, Code, Tests

**Comment by Shluffy** [comment]
@all-contributors please add @all-contributors for documentation

**Comment by xItzDiamondx** [comment]
@all-contributors please add @xItzDiamondx for content, code, design, bug reports, test

**Comment by Shluffy** [comment]
@all-contributors please add @Shluffy for content

**Comment by Shluffy** [comment]
@all-contributors please add @gosoccerboy5 for content

**Comment by xItzDiamondx** [comment]
@all-contributors please add @brourbeinsus for code, test, bug reports

**Comment by Shluffy** [comment]
@all-contributors please add @FunctionalMetatable for Answering Questions

**Comment by Shluffy** [comment]
@all-contributors please add @FunctionalMetatable for Infrastructure (on the backend)

**Comment by Shluffy** [comment]
@all-contributors please add @gosoccerboy5  for Infrastructure - the original bookmarklets.json

**Comment by Shluffy** [comment]
@all-contributors please add @xItzDiamondx for infra

**Comment by Shluffy** [comment]
@all-contributors please add @ZI-Youtuber for Code

**Comment by Shluffy** [comment]
@all-contributors please add @ZI-Youtuber for Code, tests, bug reports, documentation

**Comment by xItzDiamondx** [comment]
I think instead of a issue, it should be a discussion.

**Comment by Shluffy** [comment]
@xItzDiamondx @all-contributors bot will not respond if it is done in a discussion, see https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/discussions/80#discussioncomment-777832

**Comment by Shluffy** [comment]
> @Shluffy
> 
> I could not determine your intention.
> 
> `Basic usage: @all-contributors please add @Someone for code, doc and infra`
> 
> For other usages see the [documentation](https://allcontributors.org/docs/en/bot/usage)

lol

**Comment by Shluffy** [comment]
@all-contributors please add @Scratch-Bookmarklets/ for code

**Comment by Shluffy** [comment]
@all-contributors please add @Scratch-Bookmarklets for code

**Comment by Shluffy** [comment]
@all-contributors please add @Scratch-Bookmarklets/whole-org for code

**Comment by Shluffy** [comment]
now with 55 comments, this has been moved to #105
