### ISSUE TITLE
Keeping the updates along with the main org repo

### ISSUE THREAD

**Issue by ZI-Youtuber** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#7]
Whatever changes we are doing here you will have to update for the one in the main org.

Also just rememebr one is for the website for the bookmarklets and one is with the javavscript codes i

**Comment by Shluffy** [comment]
I think keeping it here is fine - we can make a scratch-dev-team fork if you want.

**Comment by ZI-Youtuber** [comment]
@Shluffy ok make a pull request then

**Comment by ZI-Youtuber** [comment]
@Shluffy or I can copy the code and put it in the repo myself

**Comment by ZI-Youtuber** [comment]
@
