### ISSUE TITLE
anyone know how to request something to be removed

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#77]
for all-contributors

**Comment by Shluffy** [comment]
also are there any possible things to be added that i missed (like at first I missed content)
@FunctionalMetatable

**Comment by FunctionalMetatable** [comment]
[heres all the possible contributions](https://allcontributors.org/docs/en/emoji-key). you cannot request something to be removed, but you can manually remove it
