### ISSUE TITLE
Feature Request: 404 page.

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#9]
I will get started on this.

**Comment by ZI-Youtuber** [comment]
@Shluffy ok

**Comment by Shluffy** [comment]
> Tell me if you need help.

okay.

**Comment by gosoccerboy5** [comment]
What do you think of an about page as well?

**Comment by Shluffy** [comment]
> What do you think of an about page as well?

sounds godd, do you want to do that (just make a sperate issue and self assign pls)

**Comment by gosoccerboy5** [comment]
> > What do you think of an about page as well?
> 
> sounds godd, do you want to do that (just make a sperate issue and self assign pls)

I could do that.
