### ISSUE TITLE
Bug: Header blocks content

### ISSUE THREAD

**Issue by gosoccerboy5** [Scratch-Bookmarklets/Scratch-Bookmarklets.github.io#95]
**Describe the bug**

The header. Blocks the content from being seen.
visual aid:
<img width="650" alt="Screen Shot 2021-05-24 at 3 01 51 PM" src="https://user-images.githubusercontent.com/82768218/119401411-10a5f400-bca1-11eb-870c-640344b10dcb.png">

**To Reproduce**

Go to [here](https://scratch-bookmarklets.github.io/bookmarklets.html) and feel the PAIN

**Expected behavior**

i should see the content

**Browser Information**

firefoxOS and mac browser (jk its the other way around)

**Additional context**

Surprisingly, I believe that most other people might also like being able to see the content..!

**Comment by gosoccerboy5** [comment]
Also, if you open your browser's devtools, the header shrinks. lol

**Comment by Shluffy** [comment]
@xItzDiamondx does the header

**Comment by xItzDiamondx** [comment]
Add 4 <br> before the content.

**Comment by Shluffy** [comment]
Still is there.
![Screenshot 2021-05-25 11 17 35 AM](https://user-images.githubusercontent.com/81823039/119523547-d8f38680-bd4a-11eb-8422-4ed6a08bc698.png)
and it is on the contributors page
![image](https://user-images.githubusercontent.com/81823039/119523607-e577df00-bd4a-11eb-8677-825503f67631.png)

**Comment by xItzDiamondx** [comment]
You didn't add any breaks, that's why.

**Comment by Shluffy** [comment]
> You didn't add any breaks, that's why.

you closed this so it seemed as if you did it.

**Comment by xItzDiamondx** [comment]
I added it now. Please close.

**Comment by Shluffy** [comment]
@xItzDiamondx that was on your fork. and was done where it may confuse the all-contribs  bot i will do this.

**Comment by xItzDiamondx** [comment]
In that case, the new PR I put up fixes it.
